https://programmers.co.kr/learn/courses/30/lessons/62050

In [1]:
import numpy as np

In [2]:
land = [[1, 4, 8, 10], [5, 5, 5, 5], [10, 10, 10, 10], [10, 10, 10, 20]]

In [4]:
land = np.array(land)

In [5]:
land

array([[ 1,  4,  8, 10],
       [ 5,  5,  5,  5],
       [10, 10, 10, 10],
       [10, 10, 10, 20]])

In [8]:
land[:, 0]

array([ 1,  5, 10, 10])

In [9]:
land.transpose()

array([[ 1,  5, 10, 10],
       [ 4,  5, 10, 10],
       [ 8,  5, 10, 10],
       [10,  5, 10, 20]])

In [10]:
land[1, 1]

5

--> sort into groups maybe?

In [ ]:
#솔루션 1:


def solution(land, height):
    answer = 0
    
    return answer