https://programmers.co.kr/learn/courses/30/lessons/62050

인간적으로 너무 어려운 거 아니냐 이것들아

In [1]:
import numpy as np

In [2]:
land = [[1, 4, 8, 10], [5, 5, 5, 5], [10, 10, 10, 10], [10, 10, 10, 20]]

In [3]:
land = np.array(land)

In [4]:
land

array([[ 1,  4,  8, 10],
       [ 5,  5,  5,  5],
       [10, 10, 10, 10],
       [10, 10, 10, 20]])

In [5]:
land[:, 0]

array([ 1,  5, 10, 10])

In [8]:
strip = land[:, 0]

In [9]:
strip

array([ 1,  5, 10, 10])

In [6]:
land.shape

(4, 4)

In [7]:
height = 3

In [21]:
[(i, j) for i, j in zip(strip[:-1], strip[1:]) if abs(i-j) > height]

[(1, 5), (5, 10)]

In [23]:
land[(0, 3)]

10

-> put them into groups

In [ ]:
#솔루션 1:

import numpy as np

def solution(land, height):
    land = np.array(land)
    
    answer = 0
    return answer