https://programmers.co.kr/learn/courses/30/lessons/62050

인간적으로 너무 어려운 거 아니냐 이것들아

In [1]:
import numpy as np

In [2]:
land = [[1, 4, 8, 10], [5, 5, 5, 5], [10, 10, 10, 10], [10, 10, 10, 20]]

In [3]:
land = np.array(land)

In [4]:
land

array([[ 1,  4,  8, 10],
       [ 5,  5,  5,  5],
       [10, 10, 10, 10],
       [10, 10, 10, 20]])

In [5]:
land[:, 0]

array([ 1,  5, 10, 10])

In [8]:
strip = land[:, 0]

In [9]:
strip

array([ 1,  5, 10, 10])

In [6]:
land.shape

(4, 4)

In [7]:
height = 3

In [21]:
[(i, j) for i, j in zip(strip[:-1], strip[1:]) if abs(i-j) > height]

[(1, 5), (5, 10)]

In [23]:
land[(0, 3)]

10

-> put them into groups

In [ ]:
#솔루션 1:

import numpy as np

def solution(land, height):
    land = np.array(land)
    
    answer = 0
    return answer

In [31]:
land

array([[ 1,  4,  8, 10],
       [ 5,  5,  5,  5],
       [10, 10, 10, 10],
       [10, 10, 10, 20]])

In [37]:
for num in land[:, 0]:
    print(num)

1
5
10
10


In [38]:
land[:, 0][0]

1

In [41]:
len(land[:, 0])

4

In [51]:
land

array([[ 1,  4,  8, 10],
       [ 5,  5,  5,  5],
       [10, 10, 10, 10],
       [10, 10, 10, 20]])

In [52]:
land.shape[0]

4

In [75]:
def check_hor(land, height):  #가로로 그룹핑
    groups = []
    for k in range(land.shape[0]):
        strip = land[k, :]
        temp = [(k, 0)]
        for l in range(1, len(strip)):
            last_num = land[temp[-1]]
            if abs(last_num - strip[l]) <= height:
                temp.append((k, l))
            else:
                groups.append(temp)
                temp = [(k, l)]
        groups.append(temp)
    return groups

In [76]:
check_hor(land, 3)

[[(0, 0), (0, 1)],
 [(0, 2), (0, 3)],
 [(1, 0), (1, 1), (1, 2), (1, 3)],
 [(2, 0), (2, 1), (2, 2), (2, 3)],
 [(3, 0), (3, 1), (3, 2)],
 [(3, 3)]]

In [77]:
def check_ver(land, height):   #세로로 그룹핑
    groups = []
    for k in range(land.shape[0]):
        strip = land[:, k]
        temp = [(0, k)]
        for l in range(1, len(strip)):
            last_num = land[temp[-1]]
            if abs(last_num - strip[l]) <= height:
                temp.append((l, k))
            else:
                groups.append(temp)
                temp = [(l, k)]
        groups.append(temp)
    return groups

In [78]:
check_ver(land, 3)

[[(0, 0)],
 [(1, 0)],
 [(2, 0), (3, 0)],
 [(0, 1), (1, 1)],
 [(2, 1), (3, 1)],
 [(0, 2), (1, 2)],
 [(2, 2), (3, 2)],
 [(0, 3)],
 [(1, 3)],
 [(2, 3)],
 [(3, 3)]]

In [114]:
hor_groups = check_hor(land, 3)

In [105]:
for group in hor_groups:
    print(group)

[(0, 0), (0, 1)]
[(0, 2), (0, 3)]
[(1, 0), (1, 1), (1, 2), (1, 3)]
[(2, 0), (2, 1), (2, 2), (2, 3)]
[(3, 0), (3, 1), (3, 2)]
[(3, 3)]


In [81]:
ver_groups = check_ver(land, 3)

In [83]:
for group in ver_groups:
    print(group)

[(0, 0)]
[(1, 0)]
[(2, 0), (3, 0)]
[(0, 1), (1, 1)]
[(2, 1), (3, 1)]
[(0, 2), (1, 2)]
[(2, 2), (3, 2)]
[(0, 3)]
[(1, 3)]
[(2, 3)]
[(3, 3)]


In [119]:
concatenated = []
for group_h in hor_groups:
    h = group_h.copy()
    for ele in group_h:
        ver = locate_ele_in_diff_group(ele, ver_group)
        h.extend(ver)
        if ver in ele:   #완전 포함일 경우
            pass
        else:   #새로운 element가 있을 경우
            for ele_v in ver:
                hor = locate_ele_in_di
    concatenated.append(h)
(concatenated)

[{(0, 0), (0, 1), (1, 1)},
 {(0, 2), (0, 3), (1, 2)},
 {(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (1, 3)},
 {(2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (3, 1), (3, 2)},
 {(2, 0), (2, 1), (2, 2), (3, 0), (3, 1), (3, 2)},
 {(3, 3)}]

In [120]:
def locate_ele_in_diff_group(ele, diff_groups):
    for group in diff_groups:
        if ele in group:
            return group

In [95]:
locate_ele_in_ver_group((2, 0), ver_groups)

[(2, 0), (3, 0)]

In [ ]:
def concat(hor_groups, ver_groups, height):   #가로 세로 그룹 대조해서 그룹 합치기
    
    concatenated = []

In [42]:
    return concatenated

def calc_cost(groups):   #그룹핑 결과로 최소 비용 계산하기
    
    return cost

IndentationError: expected an indented block (<ipython-input-42-fb64766d6101>, line 19)

In [32]:
land.shape

(4, 4)

In [34]:
np.array([[1, 1],
        [2, 2],
        [3, 3]]).shape

(3, 2)